name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # If you have a root package.json that includes husky and prepare scripts:
      - name: Install root dependencies (if any)
        run: npm install
        # This will trigger "prepare" script at root, thus running `husky install`
        # If no root package.json exists, you can remove this step.

      # Backend Setup & Tests
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Install backend dependencies
        working-directory: ./server
        run: npm install --ignore-scripts


      - name: Run Prisma Migrations
        working-directory: ./server
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb?schema=public"
        run: npx prisma migrate deploy

      - name: Run backend tests (Jest)
        working-directory: ./server
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/testdb?schema=public"
        run: npm test

      # Frontend Setup & Tests
      - name: Install frontend dependencies
        working-directory: ./client
        run: npm install

      - name: Build frontend
        working-directory: ./client
        run: npm run build

      - name: Start frontend server
        working-directory: ./client
        run: |
          npm start &
          # Give Next.js server some time to start up
          sleep 10

      - name: Run frontend tests (Cypress)
        working-directory: ./client
        run: npm test
