name: Backend CI

on: [push, pull_request]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: projectmanagement
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      # Step 4: Set up environment variables
      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/projectmanagement?schema=public" >> $GITHUB_ENV
          echo "PORT=8000" >> $GITHUB_ENV

      # Step 5: Run Prisma migrations
      - name: Run Prisma migrations
        working-directory: ./server
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npx prisma migrate deploy

      # Step 6: Run backend tests
      - name: Run backend tests
        working-directory: ./server
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: npm test
