name: Security Test

on: [push, pull_request]

jobs:
  security-test:
    runs-on: ubuntu-latest

    services:
      app:
        image: node:20 # Replace with your application image or deploy the app manually
        ports:
          - 3000:3000
        options: >-
          --health-cmd "curl -f http://localhost:3000 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Install dependencies and start the application
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      - name: Start backend server
        working-directory: ./server
        run: |
          npm start &
          # Wait for the server to be ready
          sleep 10

      # Step 4: Run OWASP ZAP scan
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3000'
          fail-action: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
